# Generated by Django 5.1.3 on 2025-02-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=100, unique=True)),
                ('trip', models.PositiveIntegerField()),
                ('stations', models.JSONField(default=list)),
            ],
        ),
    ]
